apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: taskwarrior

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

secretGenerator:
  - name: taskwarrior-api-secret
    literals:
      - tokens=dev-token-12345

images:
  - name: taskwarrior-api
    newName: ghcr.io/dotbinio/taskwarrior-api
    newTag: latest

commonLabels:
  app: taskwarrior-api
  app.kubernetes.io/name: taskwarrior-api
  app.kubernetes.io/instance: taskwarrior-api

